{% set name = "go-yq" %}
{% set version = "4.40.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mikefarah/yq/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 218fcd69867a9a37b3c7a3e480a1eb4a0ebd3904e46c44fb565f89e951255166

build:
  number: 0
  binary_relocation: false
  script:
    - go install -v .                               # [win]
    - go build --ldflags '-s -w'                    # [unix]
    - mkdir -p "$PREFIX/bin/"                       # [unix]
    - install ./yq "$PREFIX/bin/yq"                 # [unix]
    # Build the documentation
    - ./scripts/generate-man-page-md.sh             # [unix]
    - ./scripts/generate-man-page.sh                # [unix]
    - mkdir -p "$PREFIX/share/man/man1/"            # [unix]
    - install ./yq.1 "$PREFIX/share/man/man1/yq.1"  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - make
    - pandoc  # [unix]

test:
  commands:
    - yq --help
    - "yq eval --null-input --no-colors '.key = \"cat\"' | grep -E '^key: cat$'"  # [unix]

about:
  home: https://github.com/mikefarah/yq
  summary: Process YAML documents from the CLI
  description: |
    A lightweight and portable command-line YAML, JSON and XML processor.
    yq uses jq like syntax but works with yaml files as well as json, xml,
    properties, csv and tsv. It doesn't yet support everything jq does - but it
    does support the most common operations and functions, and more is being
    added continuously.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/mikefarah/yq
  doc_url: https://mikefarah.gitbook.io/yq/

extra:
  recipe-maintainers:
    - chrisburr
